export const runtime = 'edge';
import { NextRequest, NextResponse } from 'next/server';
import { isDbAvailable } from '@/lib/db-fallback';

// ── Fallback suggestions for when DB is unavailable ──────────────────────

function getFallbackSuggestions() {
  const now = new Date().toISOString();
  return [
    { id: 'fb-s1', source: 'ai-loop', title: 'Add response caching to /api/models and /api/history', description: 'Auto-generated by Performance improvement loop', category: 'performance', priority: 5, status: 'suggested', votes: 12, implementedAt: null, createdAt: now, updatedAt: now },
    { id: 'fb-s2', source: 'ai-loop', title: 'Add keyboard shortcuts for panel navigation', description: 'Auto-generated by UX improvement loop', category: 'ui', priority: 4, status: 'implemented', votes: 28, implementedAt: now, createdAt: now, updatedAt: now },
    { id: 'fb-s3', source: 'ai-loop', title: 'Implement model failover UI with status indicators', description: 'Auto-generated by Error Recovery improvement loop', category: 'feature', priority: 3, status: 'planned', votes: 8, implementedAt: null, createdAt: now, updatedAt: now },
    { id: 'fb-s4', source: 'ai-loop', title: 'Add voice-to-code integration for chat and editor', description: 'Auto-generated by Feature Suggestion improvement loop', category: 'feature', priority: 2, status: 'suggested', votes: 35, implementedAt: null, createdAt: now, updatedAt: now },
    { id: 'fb-s5', source: 'user-feedback', title: 'Real-time collaboration with cursor sharing', description: 'User-requested feature for collaborative editing', category: 'feature', priority: 4, status: 'suggested', votes: 22, implementedAt: null, createdAt: now, updatedAt: now },
    { id: 'fb-s6', source: 'ai-loop', title: 'Deprioritize low-quality models in auto-select', description: 'Auto-generated by Model Quality improvement loop', category: 'model', priority: 5, status: 'suggested', votes: 6, implementedAt: null, createdAt: now, updatedAt: now },
  ];
}

function computeFallbackResponse() {
  const suggestions = getFallbackSuggestions();
  const summary = {
    total: suggestions.length,
    suggested: suggestions.filter(s => s.status === 'suggested').length,
    planned: suggestions.filter(s => s.status === 'planned').length,
    implemented: suggestions.filter(s => s.status === 'implemented').length,
    rejected: suggestions.filter(s => s.status === 'rejected').length,
    byCategory: {
      ui: suggestions.filter(s => s.category === 'ui').length,
      performance: suggestions.filter(s => s.category === 'performance').length,
      feature: suggestions.filter(s => s.category === 'feature').length,
      integration: suggestions.filter(s => s.category === 'integration').length,
      model: suggestions.filter(s => s.category === 'model').length,
    },
  };
  return NextResponse.json({ suggestions, summary });
}

// ── GET — List feature suggestions ───────────────────────────────────────

export async function GET(req: NextRequest) {
  try {
    const dbOk = await isDbAvailable();
    if (!dbOk) {
      return computeFallbackResponse();
    }

    const { searchParams } = new URL(req.url);
    const category = searchParams.get('category');
    const status = searchParams.get('status');
    const source = searchParams.get('source');

    const where: Record<string, string> = {};
    if (category) where.category = category;
    if (status) where.status = status;
    if (source) where.source = source;

    const { db } = await import('@/lib/db');
    const suggestions = await db.featureSuggestion.findMany({
      where,
      orderBy: [{ votes: 'desc' }, { priority: 'desc' }, { createdAt: 'desc' }],
    });

    const summary = {
      total: suggestions.length,
      suggested: suggestions.filter(s => s.status === 'suggested').length,
      planned: suggestions.filter(s => s.status === 'planned').length,
      implemented: suggestions.filter(s => s.status === 'implemented').length,
      rejected: suggestions.filter(s => s.status === 'rejected').length,
      byCategory: {
        ui: suggestions.filter(s => s.category === 'ui').length,
        performance: suggestions.filter(s => s.category === 'performance').length,
        feature: suggestions.filter(s => s.category === 'feature').length,
        integration: suggestions.filter(s => s.category === 'integration').length,
        model: suggestions.filter(s => s.category === 'model').length,
      },
    };

    return NextResponse.json({ suggestions, summary });
  } catch (error) {
    console.error('Failed to fetch suggestions:', error);
    return computeFallbackResponse();
  }
}

// ── POST — Add a new suggestion ──────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const dbOk = await isDbAvailable();
    if (!dbOk) {
      return NextResponse.json(
        { error: 'Database not available — cannot create suggestions on edge runtime' },
        { status: 503 }
      );
    }

    const body = await req.json();
    const { source, title, description, category, priority } = body;

    if (!title || !description) {
      return NextResponse.json({ error: 'title and description are required' }, { status: 400 });
    }

    const { db } = await import('@/lib/db');
    const suggestion = await db.featureSuggestion.create({
      data: {
        source: source || 'user-feedback',
        title,
        description,
        category: category || 'feature',
        priority: priority ?? 0,
        status: 'suggested',
      },
    });

    return NextResponse.json(suggestion, { status: 201 });
  } catch (error) {
    console.error('Failed to create suggestion:', error);
    return NextResponse.json({ error: 'Failed to create suggestion' }, { status: 500 });
  }
}

// ── PUT — Vote for a suggestion or mark as implemented ───────────────────

export async function PUT(req: NextRequest) {
  try {
    const dbOk = await isDbAvailable();
    if (!dbOk) {
      return NextResponse.json(
        { error: 'Database not available — cannot update suggestions on edge runtime' },
        { status: 503 }
      );
    }

    const body = await req.json();
    const { id, action } = body;

    if (!id) {
      return NextResponse.json({ error: 'Suggestion id is required' }, { status: 400 });
    }

    const { db } = await import('@/lib/db');
    const suggestion = await db.featureSuggestion.findUnique({ where: { id } });
    if (!suggestion) {
      return NextResponse.json({ error: 'Suggestion not found' }, { status: 404 });
    }

    if (action === 'vote') {
      const updated = await db.featureSuggestion.update({
        where: { id },
        data: { votes: suggestion.votes + 1, updatedAt: new Date() },
      });
      return NextResponse.json(updated);
    }

    if (action === 'implement') {
      const updated = await db.featureSuggestion.update({
        where: { id },
        data: { status: 'implemented', implementedAt: new Date(), updatedAt: new Date() },
      });
      return NextResponse.json(updated);
    }

    if (action === 'plan') {
      const updated = await db.featureSuggestion.update({
        where: { id },
        data: { status: 'planned', updatedAt: new Date() },
      });
      return NextResponse.json(updated);
    }

    if (action === 'reject') {
      const updated = await db.featureSuggestion.update({
        where: { id },
        data: { status: 'rejected', updatedAt: new Date() },
      });
      return NextResponse.json(updated);
    }

    return NextResponse.json({ error: 'Invalid action. Use: vote, implement, plan, or reject' }, { status: 400 });
  } catch (error) {
    console.error('Failed to update suggestion:', error);
    return NextResponse.json({ error: 'Failed to update suggestion' }, { status: 500 });
  }
}
